# fly.toml file generated for your-money on 2023-04-10T00:40:12+06:00

app = "your-money"
kill_signal = "SIGTERM"
kill_timeout = 5

[env]
  DB_HOST = "your-money-dipto.internal"
  DB_NAME = "your-money"
  DB_PASSWORD = "6USNxgh6QmTPTkw"
  DB_PORT = "5432"
  DB_USER = "postgres"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  internal_port = 8080
  protocol = "tcp"

[processes]
  web = "serve"

[[services]]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
